---

- name: Container is stopped
  docker_container:
    name: "{{ jenkins_docker_container_name }}"
    image: "{{ jenkins_docker_image }}:{{ jenkins_docker_version }}"
    published_ports: "{{ jenkins_port }}:8080"
    volumes: "{{ jenkins_docker_volumes }}"
    env:
      JAVA_OPTS: "{{ jenkins_java_opts }}"
    state: stopped

- pause: seconds=5
